// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddB2Account(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddB2Account'](arg1, arg2, arg3, arg4);
}

export function AddCloudSyncTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCloudSyncTask'](arg1, arg2, arg3, arg4, arg5);
}

export function AddFTPAccount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddFTPAccount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddFilePermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFilePermission'](arg1, arg2, arg3);
}

export function AddFourSharedAccount(arg1, arg2) {
  return window['go']['main']['App']['AddFourSharedAccount'](arg1, arg2);
}

export function AddKoofrAccount(arg1, arg2) {
  return window['go']['main']['App']['AddKoofrAccount'](arg1, arg2);
}

export function AddMediaFireAccount(arg1, arg2) {
  return window['go']['main']['App']['AddMediaFireAccount'](arg1, arg2);
}

export function AddMegaAccount(arg1, arg2) {
  return window['go']['main']['App']['AddMegaAccount'](arg1, arg2);
}

export function AddS3Account(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddS3Account'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSFTPAccount(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddSFTPAccount'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddSMBAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddSMBAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSyncTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSyncTask'](arg1, arg2, arg3, arg4);
}

export function AddTelegramAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTelegramAccount'](arg1, arg2, arg3);
}

export function AddWebDAVAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWebDAVAccount'](arg1, arg2, arg3, arg4);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CompressFilesToZip(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompressFilesToZip'](arg1, arg2, arg3);
}

export function CopyFileToAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFileToAccount'](arg1, arg2, arg3);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function CreateWebShare(arg1, arg2) {
  return window['go']['main']['App']['CreateWebShare'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFilePermission(arg1, arg2) {
  return window['go']['main']['App']['DeleteFilePermission'](arg1, arg2);
}

export function DeleteWebShare(arg1) {
  return window['go']['main']['App']['DeleteWebShare'](arg1);
}

export function DisconnectAccount(arg1) {
  return window['go']['main']['App']['DisconnectAccount'](arg1);
}

export function DownloadBulkDialog(arg1) {
  return window['go']['main']['App']['DownloadBulkDialog'](arg1);
}

export function DownloadFileDialog(arg1) {
  return window['go']['main']['App']['DownloadFileDialog'](arg1);
}

export function ExtractZipFile(arg1, arg2) {
  return window['go']['main']['App']['ExtractZipFile'](arg1, arg2);
}

export function FindDuplicateFiles() {
  return window['go']['main']['App']['FindDuplicateFiles']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBackupInterval() {
  return window['go']['main']['App']['GetBackupInterval']();
}

export function GetFileActivities(arg1) {
  return window['go']['main']['App']['GetFileActivities'](arg1);
}

export function GetFilePermissions(arg1) {
  return window['go']['main']['App']['GetFilePermissions'](arg1);
}

export function GetFileWebURL(arg1) {
  return window['go']['main']['App']['GetFileWebURL'](arg1);
}

export function GetFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFiles'](arg1, arg2, arg3);
}

export function GetGeneralActivities(arg1) {
  return window['go']['main']['App']['GetGeneralActivities'](arg1);
}

export function GetLocalIPAddress() {
  return window['go']['main']['App']['GetLocalIPAddress']();
}

export function GetMountedVirtualDrives() {
  return window['go']['main']['App']['GetMountedVirtualDrives']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSyncTasks() {
  return window['go']['main']['App']['GetSyncTasks']();
}

export function GetTrashedFiles() {
  return window['go']['main']['App']['GetTrashedFiles']();
}

export function GetTunnelPublicUrl() {
  return window['go']['main']['App']['GetTunnelPublicUrl']();
}

export function GetVirtualDriveStatus() {
  return window['go']['main']['App']['GetVirtualDriveStatus']();
}

export function GetVirtualFolders() {
  return window['go']['main']['App']['GetVirtualFolders']();
}

export function GetWSAuthToken() {
  return window['go']['main']['App']['GetWSAuthToken']();
}

export function GetWebServerPort() {
  return window['go']['main']['App']['GetWebServerPort']();
}

export function GetWebShares() {
  return window['go']['main']['App']['GetWebShares']();
}

export function IsStartupEnabled() {
  return window['go']['main']['App']['IsStartupEnabled']();
}

export function IsTunnelRunning() {
  return window['go']['main']['App']['IsTunnelRunning']();
}

export function MountVirtualDrive(arg1, arg2) {
  return window['go']['main']['App']['MountVirtualDrive'](arg1, arg2);
}

export function OpenFileInBrowser(arg1) {
  return window['go']['main']['App']['OpenFileInBrowser'](arg1);
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function PermanentlyDeleteFile(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteFile'](arg1);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoteUploadFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteUploadFromURL'](arg1, arg2, arg3);
}

export function RemoveSyncTask(arg1) {
  return window['go']['main']['App']['RemoveSyncTask'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RestoreFile(arg1) {
  return window['go']['main']['App']['RestoreFile'](arg1);
}

export function RunSyncTaskNow(arg1) {
  return window['go']['main']['App']['RunSyncTaskNow'](arg1);
}

export function RunSyncTaskNowByID(arg1) {
  return window['go']['main']['App']['RunSyncTaskNowByID'](arg1);
}

export function SaveCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2, arg3);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SelectBackupFolder() {
  return window['go']['main']['App']['SelectBackupFolder']();
}

export function SendTelegramCode(arg1) {
  return window['go']['main']['App']['SendTelegramCode'](arg1);
}

export function SetAutoMountOnStartup(arg1, arg2) {
  return window['go']['main']['App']['SetAutoMountOnStartup'](arg1, arg2);
}

export function SetFileGeneralAccess(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFileGeneralAccess'](arg1, arg2, arg3);
}

export function SetStartup(arg1) {
  return window['go']['main']['App']['SetStartup'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartBackupService() {
  return window['go']['main']['App']['StartBackupService']();
}

export function StartNativeWebDAVServer(arg1, arg2) {
  return window['go']['main']['App']['StartNativeWebDAVServer'](arg1, arg2);
}

export function StartOAuthFlow(arg1) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1);
}

export function StopBackupService() {
  return window['go']['main']['App']['StopBackupService']();
}

export function StopNativeWebDAVServer() {
  return window['go']['main']['App']['StopNativeWebDAVServer']();
}

export function SyncDrives() {
  return window['go']['main']['App']['SyncDrives']();
}

export function ToggleAccountActive(arg1) {
  return window['go']['main']['App']['ToggleAccountActive'](arg1);
}

export function TogglePublicTunnel(arg1) {
  return window['go']['main']['App']['TogglePublicTunnel'](arg1);
}

export function ToggleStarred(arg1, arg2) {
  return window['go']['main']['App']['ToggleStarred'](arg1, arg2);
}

export function ToggleSyncTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleSyncTask'](arg1, arg2);
}

export function UnmountVirtualDrive(arg1) {
  return window['go']['main']['App']['UnmountVirtualDrive'](arg1);
}

export function UpdateBackupInterval(arg1) {
  return window['go']['main']['App']['UpdateBackupInterval'](arg1);
}

export function UpdateSyncTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSyncTask'](arg1, arg2, arg3, arg4);
}

export function UpdateSyncTaskExtended(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateSyncTaskExtended'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateWebSharePassword(arg1, arg2) {
  return window['go']['main']['App']['UpdateWebSharePassword'](arg1, arg2);
}

export function UploadFileDialog(arg1, arg2) {
  return window['go']['main']['App']['UploadFileDialog'](arg1, arg2);
}

export function UploadFileFromPath(arg1, arg2) {
  return window['go']['main']['App']['UploadFileFromPath'](arg1, arg2);
}

export function UploadMultipleFilesFromPaths(arg1, arg2) {
  return window['go']['main']['App']['UploadMultipleFilesFromPaths'](arg1, arg2);
}

export function VerifyTelegramCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyTelegramCode'](arg1, arg2, arg3);
}
