// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';
import {provider} from '../models';

export function AddB2Account(arg1:string,arg2:string,arg3:string,arg4:string):Promise<db.AccountRecord>;

export function AddFTPAccount(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<db.AccountRecord>;

export function AddFilePermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddFourSharedAccount(arg1:string,arg2:string):Promise<db.AccountRecord>;

export function AddKoofrAccount(arg1:string,arg2:string):Promise<db.AccountRecord>;

export function AddMediaFireAccount(arg1:string,arg2:string):Promise<db.AccountRecord>;

export function AddMegaAccount(arg1:string,arg2:string):Promise<db.AccountRecord>;

export function AddS3Account(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<db.AccountRecord>;

export function AddSFTPAccount(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string,arg6:string):Promise<db.AccountRecord>;

export function AddSMBAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<db.AccountRecord>;

export function AddSyncTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddTelegramAccount(arg1:string,arg2:string,arg3:string):Promise<db.AccountRecord>;

export function AddWebDAVAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<db.AccountRecord>;

export function CheckForUpdates():Promise<main.VersionCheckResult>;

export function CompressFilesToZip(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function CopyFileToAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function CreateWebShare(arg1:string,arg2:string):Promise<main.WebShareItem>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFilePermission(arg1:string,arg2:string):Promise<void>;

export function DeleteWebShare(arg1:string):Promise<boolean>;

export function DisconnectAccount(arg1:string):Promise<void>;

export function DownloadBulkDialog(arg1:Array<string>):Promise<void>;

export function DownloadFileDialog(arg1:string):Promise<void>;

export function ExtractZipFile(arg1:string,arg2:string):Promise<void>;

export function FindDuplicateFiles():Promise<Array<db.FileRecord>>;

export function GetAccounts():Promise<Array<db.AccountRecord>>;

export function GetAppVersion():Promise<string>;

export function GetBackupInterval():Promise<number>;

export function GetFileActivities(arg1:string):Promise<Array<db.ActivityRecord>>;

export function GetFilePermissions(arg1:string):Promise<Array<provider.SharePermission>>;

export function GetFileWebURL(arg1:string):Promise<string>;

export function GetFiles(arg1:string,arg2:boolean,arg3:string):Promise<Array<db.FileRecord>>;

export function GetGeneralActivities(arg1:number):Promise<Array<db.ActivityRecord>>;

export function GetLocalIPAddress():Promise<string>;

export function GetMountedVirtualDrives():Promise<Array<main.MountedDriveInfo>>;

export function GetRecentFiles():Promise<Array<db.FileRecord>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSyncTasks():Promise<Array<db.SyncTask>>;

export function GetTrashedFiles():Promise<Array<db.FileRecord>>;

export function GetTunnelPublicUrl():Promise<string>;

export function GetVirtualDriveStatus():Promise<main.VirtualDriveStatus>;

export function GetVirtualFolders():Promise<Array<db.FileRecord>>;

export function GetWSAuthToken():Promise<string>;

export function GetWebServerPort():Promise<number>;

export function GetWebShares():Promise<Array<main.WebShareItem>>;

export function IsStartupEnabled():Promise<boolean>;

export function IsTunnelRunning():Promise<boolean>;

export function MountVirtualDrive(arg1:string,arg2:string):Promise<main.MountedDriveInfo>;

export function OpenFileInBrowser(arg1:string):Promise<void>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function PermanentlyDeleteFile(arg1:string):Promise<void>;

export function PreviewFile(arg1:string):Promise<Record<string, any>>;

export function QuitApp():Promise<void>;

export function RemoteUploadFromURL(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveSyncTask(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RestoreFile(arg1:string):Promise<void>;

export function RunSyncTaskNow(arg1:db.SyncTask):Promise<void>;

export function RunSyncTaskNowByID(arg1:string):Promise<void>;

export function SaveCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SelectBackupFolder():Promise<string>;

export function SendTelegramCode(arg1:string):Promise<string>;

export function SetAutoMountOnStartup(arg1:boolean,arg2:string):Promise<void>;

export function SetFileGeneralAccess(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetStartup(arg1:boolean):Promise<Record<string, any>>;

export function ShowWindow():Promise<void>;

export function StartBackupService():Promise<void>;

export function StartNativeWebDAVServer(arg1:number,arg2:string):Promise<string>;

export function StartOAuthFlow(arg1:string):Promise<db.AccountRecord>;

export function StopBackupService():Promise<void>;

export function StopNativeWebDAVServer():Promise<void>;

export function SyncDrives():Promise<void>;

export function ToggleAccountActive(arg1:string):Promise<boolean>;

export function TogglePublicTunnel(arg1:boolean):Promise<string>;

export function ToggleStarred(arg1:string,arg2:boolean):Promise<void>;

export function ToggleSyncTask(arg1:string,arg2:boolean):Promise<void>;

export function UnmountVirtualDrive(arg1:string):Promise<void>;

export function UpdateBackupInterval(arg1:number):Promise<void>;

export function UpdateSyncTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateWebSharePassword(arg1:string,arg2:string):Promise<void>;

export function UploadFileDialog(arg1:string,arg2:string):Promise<void>;

export function UploadFileFromPath(arg1:string,arg2:string):Promise<void>;

export function UploadMultipleFilesFromPaths(arg1:string,arg2:Array<string>):Promise<void>;

export function VerifyTelegramCode(arg1:string,arg2:string,arg3:string):Promise<db.AccountRecord>;
