// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFilePermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFilePermission'](arg1, arg2, arg3);
}

export function AddS3Account(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddS3Account'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSyncTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSyncTask'](arg1, arg2, arg3, arg4);
}

export function AddTelegramAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTelegramAccount'](arg1, arg2, arg3);
}

export function AddWebDAVAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWebDAVAccount'](arg1, arg2, arg3, arg4);
}

export function CompressFilesToZip(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompressFilesToZip'](arg1, arg2, arg3);
}

export function CopyFileToAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFileToAccount'](arg1, arg2, arg3);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFilePermission(arg1, arg2) {
  return window['go']['main']['App']['DeleteFilePermission'](arg1, arg2);
}

export function DisconnectAccount(arg1) {
  return window['go']['main']['App']['DisconnectAccount'](arg1);
}

export function DownloadBulkDialog(arg1) {
  return window['go']['main']['App']['DownloadBulkDialog'](arg1);
}

export function DownloadFileDialog(arg1) {
  return window['go']['main']['App']['DownloadFileDialog'](arg1);
}

export function ExtractZipFile(arg1, arg2) {
  return window['go']['main']['App']['ExtractZipFile'](arg1, arg2);
}

export function FindDuplicateFiles() {
  return window['go']['main']['App']['FindDuplicateFiles']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBackupInterval() {
  return window['go']['main']['App']['GetBackupInterval']();
}

export function GetFileActivities(arg1) {
  return window['go']['main']['App']['GetFileActivities'](arg1);
}

export function GetFilePermissions(arg1) {
  return window['go']['main']['App']['GetFilePermissions'](arg1);
}

export function GetFileWebURL(arg1) {
  return window['go']['main']['App']['GetFileWebURL'](arg1);
}

export function GetFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFiles'](arg1, arg2, arg3);
}

export function GetGeneralActivities(arg1) {
  return window['go']['main']['App']['GetGeneralActivities'](arg1);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSyncTasks() {
  return window['go']['main']['App']['GetSyncTasks']();
}

export function GetTrashedFiles() {
  return window['go']['main']['App']['GetTrashedFiles']();
}

export function GetVirtualFolders() {
  return window['go']['main']['App']['GetVirtualFolders']();
}

export function GetWSAuthToken() {
  return window['go']['main']['App']['GetWSAuthToken']();
}

export function OpenFileInBrowser(arg1) {
  return window['go']['main']['App']['OpenFileInBrowser'](arg1);
}

export function PermanentlyDeleteFile(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteFile'](arg1);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoteUploadFromURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoteUploadFromURL'](arg1, arg2, arg3);
}

export function RemoveSyncTask(arg1) {
  return window['go']['main']['App']['RemoveSyncTask'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RestoreFile(arg1) {
  return window['go']['main']['App']['RestoreFile'](arg1);
}

export function RunSyncTaskNow(arg1) {
  return window['go']['main']['App']['RunSyncTaskNow'](arg1);
}

export function SaveCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2, arg3);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SelectBackupFolder() {
  return window['go']['main']['App']['SelectBackupFolder']();
}

export function SendTelegramCode(arg1) {
  return window['go']['main']['App']['SendTelegramCode'](arg1);
}

export function SetFileGeneralAccess(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFileGeneralAccess'](arg1, arg2, arg3);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartBackupService() {
  return window['go']['main']['App']['StartBackupService']();
}

export function StartOAuthFlow(arg1) {
  return window['go']['main']['App']['StartOAuthFlow'](arg1);
}

export function StopBackupService() {
  return window['go']['main']['App']['StopBackupService']();
}

export function SyncDrives() {
  return window['go']['main']['App']['SyncDrives']();
}

export function ToggleStarred(arg1, arg2) {
  return window['go']['main']['App']['ToggleStarred'](arg1, arg2);
}

export function ToggleSyncTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleSyncTask'](arg1, arg2);
}

export function UpdateBackupInterval(arg1) {
  return window['go']['main']['App']['UpdateBackupInterval'](arg1);
}

export function UpdateSyncTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateSyncTask'](arg1, arg2, arg3, arg4);
}

export function UploadFileDialog(arg1, arg2) {
  return window['go']['main']['App']['UploadFileDialog'](arg1, arg2);
}

export function UploadFileFromPath(arg1, arg2) {
  return window['go']['main']['App']['UploadFileFromPath'](arg1, arg2);
}

export function VerifyTelegramCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyTelegramCode'](arg1, arg2, arg3);
}
