// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {provider} from '../models';

export function AddFilePermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddS3Account(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<db.AccountRecord>;

export function AddSyncTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddTelegramAccount(arg1:string,arg2:string,arg3:string):Promise<db.AccountRecord>;

export function AddWebDAVAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<db.AccountRecord>;

export function CompressFilesToZip(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function CopyFileToAccount(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFilePermission(arg1:string,arg2:string):Promise<void>;

export function DisconnectAccount(arg1:string):Promise<void>;

export function DownloadBulkDialog(arg1:Array<string>):Promise<void>;

export function DownloadFileDialog(arg1:string):Promise<void>;

export function ExtractZipFile(arg1:string,arg2:string):Promise<void>;

export function FindDuplicateFiles():Promise<Array<db.FileRecord>>;

export function GetAccounts():Promise<Array<db.AccountRecord>>;

export function GetBackupInterval():Promise<number>;

export function GetFileActivities(arg1:string):Promise<Array<db.ActivityRecord>>;

export function GetFilePermissions(arg1:string):Promise<Array<provider.SharePermission>>;

export function GetFileWebURL(arg1:string):Promise<string>;

export function GetFiles(arg1:string,arg2:boolean,arg3:string):Promise<Array<db.FileRecord>>;

export function GetGeneralActivities(arg1:number):Promise<Array<db.ActivityRecord>>;

export function GetRecentFiles():Promise<Array<db.FileRecord>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetSyncTasks():Promise<Array<db.SyncTask>>;

export function GetTrashedFiles():Promise<Array<db.FileRecord>>;

export function GetVirtualFolders():Promise<Array<db.FileRecord>>;

export function GetWSAuthToken():Promise<string>;

export function OpenFileInBrowser(arg1:string):Promise<void>;

export function PermanentlyDeleteFile(arg1:string):Promise<void>;

export function PreviewFile(arg1:string):Promise<Record<string, any>>;

export function QuitApp():Promise<void>;

export function RemoteUploadFromURL(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveSyncTask(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RestoreFile(arg1:string):Promise<void>;

export function RunSyncTaskNow(arg1:db.SyncTask):Promise<void>;

export function SaveCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSetting(arg1:string,arg2:string):Promise<void>;

export function SelectBackupFolder():Promise<string>;

export function SendTelegramCode(arg1:string):Promise<string>;

export function SetFileGeneralAccess(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartBackupService():Promise<void>;

export function StartOAuthFlow(arg1:string):Promise<db.AccountRecord>;

export function StopBackupService():Promise<void>;

export function SyncDrives():Promise<void>;

export function ToggleStarred(arg1:string,arg2:boolean):Promise<void>;

export function ToggleSyncTask(arg1:string,arg2:boolean):Promise<void>;

export function UpdateBackupInterval(arg1:number):Promise<void>;

export function UpdateSyncTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadFileDialog(arg1:string,arg2:string):Promise<void>;

export function UploadFileFromPath(arg1:string,arg2:string):Promise<void>;

export function VerifyTelegramCode(arg1:string,arg2:string,arg3:string):Promise<db.AccountRecord>;
